//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDC.FluxQuery {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HDC.FluxQuery.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;columns&gt;
        ///  &lt;column dataPropertyName=&quot;StationName&quot; text=&quot;站名&quot; &gt;&lt;/column&gt;
        ///  &lt;column dataPropertyName=&quot;DT&quot; text=&quot;时间&quot; format=&quot;G&quot; width=&quot;160&quot;&gt;&lt;/column&gt;
        ///  &lt;column dataPropertyName=&quot;AlarmInfo&quot; text=&quot;信息&quot; &gt;&lt;/column&gt;
        ///&lt;/columns&gt; 的本地化字符串。
        /// </summary>
        internal static string AlarmColumnConfig {
            get {
                return ResourceManager.GetString("AlarmColumnConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 条报警数据 的本地化字符串。
        /// </summary>
        internal static string AlarmWithCount {
            get {
                return ResourceManager.GetString("AlarmWithCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无报警数据 的本地化字符串。
        /// </summary>
        internal static string HasNotAlarm {
            get {
                return ResourceManager.GetString("HasNotAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流量查询(&amp;L) 的本地化字符串。
        /// </summary>
        internal static string mnu_flux_query {
            get {
                return ResourceManager.GetString("mnu_flux_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供电查询(&amp;D) 的本地化字符串。
        /// </summary>
        internal static string mnu_hd_query {
            get {
                return ResourceManager.GetString("mnu_hd_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;columns&gt;
        ///  &lt;column dataPropertyName=&quot;StationName&quot; text=&quot;站名&quot; &gt;&lt;/column&gt;
        ///  &lt;column dataPropertyName=&quot;DT&quot; text=&quot;时间&quot; format=&quot;G&quot; width=&quot;160&quot;&gt;&lt;/column&gt;
        ///  &lt;column dataPropertyName=&quot;AlarmInfo&quot; text=&quot;信息&quot; &gt;&lt;/column&gt;
        ///&lt;/columns&gt; 的本地化字符串。
        /// </summary>
        internal static string MonthReportColumnConfig {
            get {
                return ResourceManager.GetString("MonthReportColumnConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 断电报警 的本地化字符串。
        /// </summary>
        internal static string PowerAlarm {
            get {
                return ResourceManager.GetString("PowerAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 断电 的本地化字符串。
        /// </summary>
        internal static string PowerOff {
            get {
                return ResourceManager.GetString("PowerOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流量查询 的本地化字符串。
        /// </summary>
        internal static string title_flux_form {
            get {
                return ResourceManager.GetString("title_flux_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供电查询 的本地化字符串。
        /// </summary>
        internal static string title_hd_query {
            get {
                return ResourceManager.GetString("title_hd_query", resourceCulture);
            }
        }
    }
}
