<?xml version="1.0" encoding="utf-8"?>
<Database Name="bcDB" Class="BcdbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=bcDB;User ID=sa" SettingsObjectName="BaiCheng.Properties.Settings" SettingsPropertyName="bcDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblStation" Member="tblStation">
    <Type Name="tblStation">
      <Column Name="StationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Street" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StationOrdinal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StationName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="StationRemark" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="StationCPConfig" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Association Name="tblStation_tblDevice" Member="tblDevice" OtherKey="StationID" Type="tblDevice" />
    </Type>
  </Table>
  <Table Name="dbo.tblDevice" Member="tblDevice">
    <Type Name="tblDevice">
      <Column Name="DeviceID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeviceName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DeviceAddress" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeviceType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DeviceRemark" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="DeviceExtend" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Association Name="tblDevice_tblMeasureSluiceData" Member="tblMeasureSluiceData" OtherKey="DeviceID" Type="tblMeasureSluiceData" />
      <Association Name="tblStation_tblDevice" Member="tblStation" ThisKey="StationID" Type="tblStation" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblMeasureSluiceData" Member="tblMeasureSluiceData">
    <Type Name="tblMeasureSluiceData">
      <Column Name="MeasureSluiceDataID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DeviceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="BeforeWL" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="BehindWL" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="InstantFlux" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="Height" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="RemainedAmount" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="UsedAmount" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Association Name="tblMeasureSluiceData_tblMeasureSluiceDataLast" Member="tblMeasureSluiceDataLast" OtherKey="MeasureSluiceDataID" Type="tblMeasureSluiceDataLast" />
      <Association Name="tblDevice_tblMeasureSluiceData" Member="tblDevice" ThisKey="DeviceID" Type="tblDevice" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblMeasureSluiceDataLast" Member="tblMeasureSluiceDataLast">
    <Type Name="tblMeasureSluiceDataLast">
      <Column Name="MeasureSluiceDataLastID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MeasureSluiceDataID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeviceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tblMeasureSluiceData_tblMeasureSluiceDataLast" Member="tblMeasureSluiceData" ThisKey="MeasureSluiceDataID" Type="tblMeasureSluiceData" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vStationDevice" Member="vStationDevice">
    <Type Name="vStationDevice">
      <Column Name="StationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StationName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DeviceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeviceName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DeviceAddress" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeviceType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DeviceExtend" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vMeasureSluiceData" Member="vMeasureSluiceData">
    <Type Name="vMeasureSluiceData">
      <Column Name="StationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeviceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MeasureSluiceDataID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StationName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DeviceName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BeforeWL" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="BehindWL" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="InstantFlux" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="Height" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="RemainedAmount" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="UsedAmount" Type="System.Single" DbType="Real" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vMeasureSluiceDataLast" Member="vMeasureSluiceDataLast">
    <Type Name="vMeasureSluiceDataLast">
      <Column Name="DeviceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MeasureSluiceDataID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StationName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DeviceName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="BeforeWL" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="BehindWL" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="InstantFlux" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="Height" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="RemainedAmount" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="UsedAmount" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>